- name: Deploy Kubernetes
  hosts: control worker
  become: yes
  tasks:
  - name: Create containerd.conf
    ansible.builtin.copy:
      src: /home/gutman/kubernetes/files/containerd.conf
      dest: /etc/modules-load.d/containerd.conf
      owner: root
      group: root
      mode: '0644'

  - name: Load Module overlay
    community.general.modprobe:
      name: overlay
      state: present
  - name: Load Module br_netfilter
    community.general.modprobe:
      name: br_netfilter
      state: present

  - name: Create sysctl networking rules for kubernetes
    ansible.builtin.copy:
      src: /home/gutman/kubernetes/files/99-kubernetes-cri.conf
      dest: /etc/sysctl.d/99-kubernetes-cri.conf
  - name: Set sysctl changes immidiately
    shell:
      cmd: sysctl --system
  - name: Install containerd Package
    ansible.builtin.package:
      name: containerd
      state: present
  - name: Create Folder
    file:
      path: /etc/containerd
      state: directory
      mode: '0755'
  - name: Save containerd default config
    shell:
      cmd: containerd config default > /etc/containerd/config.toml
  - name: Restart containerd service
    systemd:
      state: restarted
      daemon_reload: yes
      name: containerd
  - name: Install apt-transport-https and curl
    package:
      name:
        - apt-transport-https
        - curl
      state: present
  - name: Download and add an kubernetes apt gpg signing key
    command : "curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -"
  - name: Create kubernetes sources file
    copy:
      src: /home/gutman/kubernetes/files/kubernetes.list
      dest: /etc/apt/sources.list.d/kubernetes.list
      owner: root
      group: root
      mode: '0644'
  - name: Install Kubernetes Packages
    apt:
      update_cache: yes
      name: 
        - kubelet=1.23.0-00
        - kubeadm=1.23.0-00
        - kubectl=1.23.0-00
      state: present
  - name: Hold kubeadm
    dpkg_selections:
      name: kubeadm 
      selection: hold
  - name: Hold kubelet
    dpkg_selections:
      name: kubelet
      selection: hold
  - name: Holde kubectl
    dpkg_selections:
      name: kubectl
      selection: hold
